version: '3.8'

services:
  flask-app-dev:
    container_name: flask-app-dev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Python: 3, 3.10, 3.9, 3.8, 3.7, 3.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 3.10-bullseye
        # Optional Node.js version to install
        NODE_VERSION: "lts/*"

    volumes:
      - ..:/workspace:cached  

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # this wont work
    # command: sh -c 'cd .. && flask run'

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:flask-db-dev
    networks:
      - default

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    # dont forward here, it will bind for sleep infinity
    # ports:
    #   - '5000:5000'
    depends_on:
      - flask-db-dev

  flask-db-dev:
    image: postgres:15.1-bullseye
    container_name: flask-db-dev
    restart: unless-stopped
    ports:
      - '5436:5432'
    volumes:
      - flask-pg-data-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default
      - external-flask-dev

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  
  flask-adminer-dev:
    image: adminer:4.8.1-standalone
    container_name: flask-adminer-dev
    ports:
      - '8080:8080'
    depends_on:
      - flask-db-dev
    networks:
      - default
      - external-flask-dev

volumes:
  flask-pg-data-dev:

networks:
  external-flask-dev:
    external: true